name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install cross (Linux)
        if: runner.os == 'Linux'
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: cross build --release --target ${{ matrix.target }}
      - name: Build (non-Linux)
        if: runner.os != 'Linux'
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package (Unix)
        if: runner.os != 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../shell-runner-${{ matrix.target }}.tar.gz shell-runner
      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ../../../shell-runner-${{ matrix.target }}.zip shell-runner.exe
      - name: Upload release assets (Unix)
        if: runner.os != 'Windows'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} shell-runner-${{ matrix.target }}.tar.gz
      - name: Upload release assets (Windows)
        if: runner.os == 'Windows'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} shell-runner-${{ matrix.target }}.zip
